packages:
  - chat-ui
  - remote-mcp-with-ui-starter
  - webmcp-template
  - webmcp-template-vanilla
  - create-webmcp-app
  - e2e-tests

catalog:
  "@types/node": ^24.9.2
  typescript: ~5.8.3
  zod: ^3.25.1

onlyBuiltDependencies:
